language: php

sudo: false

php:
- 7.1
- 7.2
- 7.3
- 7.4

services:
- sqlite

before_script:
- travis_retry composer install --no-interaction --prefer-dist
- composer show laravel/framework

script:
- find src/ -type f -name '*.php' -print0 | xargs -0 -L1 -P4 -- php -l
- vendor/bin/phpunit
